sudo: required 
language: generic 
services:
  - docker 

before_install:
  - docker build -t sangeeth2121/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sangeeth2121/react-test npm test -- --coverage

after_success:
  - docker build -t sangeethp1/multi-client ./client
  - docker build -t sangeethp1/multi-server ./server
  - docker build -t sangeethp1/multi-nginx ./nginx
  - docker build -t sangeethp1/multi-worker ./worker 
  - echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin

  - docker push sangeethp1/multi-client
  - docker push sangeethp1/multi-server
  - docker push sangeethp1/multi-nginx
  - docker push sangeethp1/multi-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-808938276827
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY