sudo: required 
language: generic 
services:
  - docker 

before_install:
  - docker build -t sangeeth2121/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sangeeth2121/react-test npm test -- --coverage

after_success:
  - docker build -t sangeeth2121/multi-client ./client
  - docker build -t sangeeth2121/multi-server ./server
  - docker build -t sangeeth2121/multi-nginx ./nginx
  - docker build -t sangeeth2121/multi-worker ./worker 
  - echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin

  - docker push sangeeth2121/multi-client
  - docker push sangeeth2121/multi-server
  - docker push sangeeth2121/multi-nginx
  - docker push sangeeth2121/multi-worker